package model;

import java.util.HashMap;

public class Data {

    public Data(){}

    public static HashMap<String, String> getTeamMap() {
        HashMap<String, String> teams = new HashMap<>();
        teams.put("CRC", "crc");
        teams.put("OVDR", "ovdr");
        return teams;
    }

    public static HashMap<String, String> getUltimateMap() {
        HashMap<String, String> characters = new HashMap<>();
        characters.put("mario", "mario");
        characters.put("donkey kong", "donkey_kong");
        characters.put("link", "link");
        characters.put("samus", "samus");
        characters.put("samus sombre", "dark_samus");
        characters.put("yoshi", "yoshi");
        characters.put("kirby", "kirby");
        characters.put("fox", "fox");
        characters.put("pikachu", "pikachu");
        characters.put("luigi", "luigi");
        characters.put("ness", "ness");
        characters.put("captain falcon", "captain_falcon");
        characters.put("rondoudou", "jiggly_puff");
        characters.put("peach", "peach");
        characters.put("daisy", "daisy");
        characters.put("bowser", "bowser");
        characters.put("ice climbers", "ice_climbers");
        characters.put("sheik", "sheik");
        characters.put("zelda", "zelda");
        characters.put("dr.mario", "dr_mario");
        characters.put("pichu", "pichu");
        characters.put("falco", "falco");
        characters.put("marth", "marth");
        characters.put("lucina", "lucina");
        characters.put("link enfant", "young_link");
        characters.put("ganondorf", "ganondorf");
        characters.put("mewtwo", "mewtwo");
        characters.put("roy", "roy");
        characters.put("chrom", "chrom");
        characters.put("mr.game and watch", "mr_game_and_watch");
        characters.put("meta knight", "metaknight");
        characters.put("pit", "pit");
        characters.put("pit maléfique", "dark_pit");
        characters.put("samus sans armure", "zero_suit_samus");
        characters.put("wario", "wario");
        characters.put("snake", "snake");
        characters.put("ike", "ike");
        characters.put("dresseur de pokémon", "pokemon_trainer");
        characters.put("diddy kong", "diddy_kong");
        characters.put("lucas", "lucas");
        characters.put("sonic", "sonic");
        characters.put("roi dadidou", "king_dedede");
        characters.put("olimar", "olimar");
        characters.put("lucario", "lucario");
        characters.put("rob", "rob");
        characters.put("link cartoon", "toon_link");
        characters.put("wolf", "wolf");
        characters.put("villageois", "villager");
        characters.put("mega man", "mega_man");
        characters.put("entraîneuse wii fit", "wii_fit_trainer");
        characters.put("harmonie et luma", "rosalina_luma");
        characters.put("little mac", "little_mac");
        characters.put("amphinobi", "greninja");
        characters.put("palutena", "palutena");
        characters.put("pac man", "pac_man");
        characters.put("daraen", "robin");
        characters.put("bowser jr", "bowser_jr");
        characters.put("duo duck hunt", "duck_hunt");
        characters.put("ryu", "ryu");
        characters.put("ken", "ken");
        characters.put("cloud", "cloud");
        characters.put("corrin", "corrin");
        characters.put("bayonneta", "bayonneta");
        characters.put("inkling", "inkling");
        characters.put("ridley", "ridley");
        characters.put("simon", "simon");
        characters.put("richter", "richter");
        characters.put("king k.rool", "king_k_rool");
        characters.put("marie", "isabelle");
        characters.put("felinferno", "incineroar");
        characters.put("plante piranha", "piranha_plant");
        characters.put("joker", "joker");
        characters.put("héros", "hero");
        characters.put("banjo & kazooie", "banjo_kazooie");
        characters.put("terry", "terry");
        characters.put("byleth", "byleth");
        characters.put("min min", "minmin");
        characters.put("steve", "steve");
        characters.put("sephiroth", "sephiroth");
        characters.put("pyra/mythra", "pyra_mythra");
        characters.put("kazuya", "kazuya");
        characters.put("sora", "sora");
        characters.put("boxeur mii", "mii_brawler");
        characters.put("épéiste mii", "mii_swordfighter");
        characters.put("tireur mii", "mii_gunner");
        characters.put("aléatoire", "random");

        return characters;
    }

    public static HashMap<String, String> getMeleeMap() {
        HashMap<String, String> characters = new HashMap<>();
        characters.put("mario", "mario");
        characters.put("donkey kong", "donkey_kong");
        characters.put("link", "link");
        characters.put("samus", "samus");
        characters.put("yoshi", "yoshi");
        characters.put("kirby", "kirby");
        characters.put("fox", "fox");
        characters.put("pikachu", "pikachu");
        characters.put("luigi", "luigi");
        characters.put("ness", "ness");
        characters.put("captain falcon", "captain_falcon");
        characters.put("rondoudou", "jiggly_puff");
        characters.put("peach", "peach");
        characters.put("bowser", "bowser");
        characters.put("ice climbers", "ice_climbers");
        characters.put("sheik", "sheik");
        characters.put("zelda", "zelda");
        characters.put("dr.mario", "dr_mario");
        characters.put("pichu", "pichu");
        characters.put("falco", "falco");
        characters.put("marth", "marth");
        characters.put("lucina", "lucina");
        characters.put("link enfant", "young_link");
        characters.put("ganondorf", "ganondorf");
        characters.put("mewtwo", "mewtwo");
        characters.put("roy", "roy");
        characters.put("mr.game and watch", "mr_game_and_watch");
        characters.put("aléatoire", "random");

        return characters;
    }

    public static Rescale getRescale(String character) {
        HashMap<String, Rescale> rescale = new HashMap<>();

        rescale.put("melee_mario", new Rescale(25, 0, 230, 300));
        rescale.put("melee_donkey_kong", new Rescale(5, 0, 150, 470));
        rescale.put("melee_link", new Rescale(0, 0, 0, 0));
        rescale.put("melee_samus", new Rescale(0, 0, 300, 274));
        rescale.put("melee_yoshi", new Rescale(0, 0, 0, 0));
        rescale.put("melee_kirby", new Rescale(62, 0, 0, 466));
        rescale.put("melee_fox", new Rescale(25, 0, 350, 340));
        rescale.put("melee_pikachu", new Rescale(0, 0, 250, 240));
        rescale.put("melee_luigi", new Rescale(50, 0, 290, 280));
        rescale.put("melee_ness", new Rescale(0, 0, 200, 306));
        rescale.put("melee_captain_falcon", new Rescale(0, 0, 400, 286));
        rescale.put("melee_jigglypuff", new Rescale(50, 0, 40, 350));
        rescale.put("melee_peach", new Rescale(0, 0, 400, 222));
        rescale.put("melee_bowser", new Rescale(0, 0, 0, 0));
        rescale.put("melee_ice_climbers", new Rescale(75, 0, 100, 444));
        rescale.put("melee_sheik", new Rescale(0, 0, 300, 448));
        rescale.put("melee_zelda", new Rescale(0, 0, 400, 205));
        rescale.put("melee_dr_mario", new Rescale(0, 0, 200, 439));
        rescale.put("melee_pichu", new Rescale(0, 0, 0, 397));
        rescale.put("melee_falco", new Rescale(0, 0, 350, 302));
        rescale.put("melee_marth", new Rescale(0, 0, 250, 245));
        rescale.put("melee_young_link", new Rescale(72, 0, 300, 310));
        rescale.put("melee_ganondorf", new Rescale(0, 0, 300, 374));
        rescale.put("melee_mewtwo", new Rescale(0, 0, 300, 360));
        rescale.put("melee_roy", new Rescale(0, 0, 350, 250));
        rescale.put("melee_mr_game_and_watch", new Rescale(0, 0, 100, 522));
        rescale.put("ultimate_mario", new Rescale(50, 0, 320, 270));
        rescale.put("ultimate_donkey_kong", new Rescale(50, 120, 180, 470));
        rescale.put("ultimate_link", new Rescale(50, 0, 320, 320));
        rescale.put("ultimate_samus", new Rescale(22, 0, 300, 390));
        rescale.put("ultimate_dark_samus", new Rescale(0, 0, 300, 326));
        rescale.put("ultimate_yoshi", new Rescale(0, 0, 150, 510));
        rescale.put("ultimate_kirby", new Rescale(0, 0, 0, 630));
        rescale.put("ultimate_fox", new Rescale(50, 0, 300, 450));
        rescale.put("ultimate_pikachu", new Rescale(50, 100, 50, 370));
        rescale.put("ultimate_luigi", new Rescale(0, 0, 0, 900));
        rescale.put("ultimate_ness", new Rescale(0, 0, 200, 511));
        rescale.put("ultimate_captain_falcon", new Rescale(0, 0, 300, 438));
        rescale.put("ultimate_jigglypuff", new Rescale(0, 0, 100, 455));
        rescale.put("ultimate_peach", new Rescale(0, 100, 300, 362));
        rescale.put("ultimate_daisy", new Rescale(0, 0, 350, 366));
        rescale.put("ultimate_bowser", new Rescale(35, 120, 230, 380));
        rescale.put("ultimate_ice_climbers", new Rescale(50, 30, 150, 270));
        rescale.put("ultimate_sheik", new Rescale(110, 0, 250, 400));
        rescale.put("ultimate_zelda", new Rescale(20, 0, 250, 360));
        rescale.put("ultimate_dr_mario", new Rescale(0, 0, 200, 341));
        rescale.put("ultimate_pichu", new Rescale(50, 0, 50, 400));
        rescale.put("ultimate_falco", new Rescale(0, 0, 100, 740));
        rescale.put("ultimate_marth", new Rescale(190, 0, 300, 390));
        rescale.put("ultimate_lucina", new Rescale(190, 100, 300, 330));
        rescale.put("ultimate_young_link", new Rescale(0, 0, 200, 252));
        rescale.put("ultimate_ganondorf", new Rescale(0, 0, 200, 445));
        rescale.put("ultimate_mewtwo", new Rescale(70, 0, 200, 450));
        rescale.put("ultimate_roy", new Rescale(35, 0, 200, 380));
        rescale.put("ultimate_chrom", new Rescale(80, 0, 200, 280));
        rescale.put("ultimate_mr_game_and_watch", new Rescale(0, 0, 120, 304));
        rescale.put("ultimate_metaknight", new Rescale(96, 100, 100, 360));
        rescale.put("ultimate_pit", new Rescale(205, 0, 0, 515));
        rescale.put("ultimate_dark_pit", new Rescale(0, 0, 100, 282));
        rescale.put("ultimate_zero_suit_samus", new Rescale(220, 0, 220, 400));
        rescale.put("ultimate_wario", new Rescale(0, 0, 150, 561));
        rescale.put("ultimate_snake", new Rescale(0, 0, 100, 540));
        rescale.put("ultimate_ike", new Rescale(120, 0, 250, 220));
        rescale.put("ultimate_pokemon_trainer", new Rescale(0, 0, 200, 420));
        rescale.put("ultimate_diddy_kong", new Rescale(30, 0, 100, 625));
        rescale.put("ultimate_lucas", new Rescale(0, 0, 200, 378));
        rescale.put("ultimate_sonic", new Rescale(0, 0, 100, 485));
        rescale.put("ultimate_king_dedede", new Rescale(0, 0, 200, 589));
        rescale.put("ultimate_olimar", new Rescale(20, 0, 150, 400));
        rescale.put("ultimate_lucario", new Rescale(0, 0, 200, 400));
        rescale.put("ultimate_rob", new Rescale(10, 0, 0, 570));
        rescale.put("ultimate_toon_link", new Rescale(70, 0, 200, 430));
        rescale.put("ultimate_wolf", new Rescale(82, 0, 300, 325));
        rescale.put("ultimate_villager", new Rescale(50, 0, 200, 600));
        rescale.put("ultimate_mega_man", new Rescale(192, 0, 200, 460));
        rescale.put("ultimate_wii_fit_trainer", new Rescale(0, 100, 300, 141));
        rescale.put("ultimate_rosalina_luma", new Rescale(148, 0, 200, 425));
        rescale.put("ultimate_little_mac", new Rescale(0, 0, 200, 329));
        rescale.put("ultimate_greninja", new Rescale(75, 0, 50, 515));
        rescale.put("ultimate_palutena", new Rescale(27, 0, 200, 370));
        rescale.put("ultimate_pac_man", new Rescale(0, 50, 200, 361));
        rescale.put("ultimate_robin", new Rescale(0, 0, 200, 516));
        rescale.put("ultimate_bowser_jr", new Rescale(66, 0, 100, 406));
        rescale.put("ultimate_duck_hunt", new Rescale(0, 100, 100, 251));
        rescale.put("ultimate_ryu", new Rescale(105, 0, 300, 406));
        rescale.put("ultimate_ken", new Rescale(0, 100, 300, 209));
        rescale.put("ultimate_cloud", new Rescale(95, 100, 300, 490));
        rescale.put("ultimate_corrin", new Rescale(0, 0, 300, 502));
        rescale.put("ultimate_bayonetta", new Rescale(35, 0, 300, 400));
        rescale.put("ultimate_inkling", new Rescale(35, 0, 200, 470));
        rescale.put("ultimate_ridley", new Rescale(145, 50, 300, 400));
        rescale.put("ultimate_simon", new Rescale(0, 0, 300, 305));
        rescale.put("ultimate_richter", new Rescale(160, 150, 250, 330));
        rescale.put("ultimate_king_k_rool", new Rescale(0, 0, 250, 360));
        rescale.put("ultimate_isabelle", new Rescale(0, 0, 200, 300));
        rescale.put("ultimate_incineroar", new Rescale(0, 0, 200, 509));
        rescale.put("ultimate_piranha_plant", new Rescale(0, 0, 100, 335));
        rescale.put("ultimate_joker", new Rescale(121, 20, 250, 390));
        rescale.put("ultimate_hero", new Rescale(0, 0, 200, 375));
        rescale.put("ultimate_banjo_kazooie", new Rescale(55, 0, 150, 380));
        rescale.put("ultimate_terry", new Rescale(0, 0, 300, 251));
        rescale.put("ultimate_byleth", new Rescale(0, 150, 250, 230));
        rescale.put("ultimate_minmin", new Rescale(0, 0, 0, 720));
        rescale.put("ultimate_steve", new Rescale(0, 0, 50, 612));
        rescale.put("ultimate_sephiroth", new Rescale(10, 250, 200, 200));
        rescale.put("ultimate_pyra_mythra", new Rescale(75, 0, 300, 400));
        rescale.put("ultimate_kazuya", new Rescale(0, 0, 350, 204));
        rescale.put("ultimate_sora", new Rescale(90, 0, 250, 360));
        rescale.put("ultimate_mii_brawler", new Rescale(55, 0, 0, 690));
        rescale.put("ultimate_mii_swordfighter", new Rescale(320, 0, 100, 380));
        rescale.put("ultimate_mii_gunner", new Rescale(116, 0, 200, 400));
        rescale.put("random", new Rescale(0, 0, 0, 389));

        return rescale.get(character);
    }
}
